name: Run Scheduled Script
    on:
      schedule:
        - cron: '*/5 * * * *' # Runs every 5 minutes
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.x' # Replace with your desired Python version
          - name: Install dependencies
            run: pip install requests #if you have other dependencies add them here.
          - name: Run script
            run: python get_veh_location.py # Replace with your script's filename
