name: Run Python Script Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # This means every 5 minutes
  # Allows manual triggering of the workflow
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Use Ubuntu for the runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository's code

      - name: Set up Python
        uses: actions/setup-python@v4  # Set up Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Python script
        run: python get_veh_location.py  # Replace with the name of your Python script
